[project]
name = "cppdoc-example"
version = "0.1.0"

[input]
glob = "include/**/*.hpp"
compiler_arguments = ["-Iinclude", "-std=gnu++20", "-xc++"]

[pages]
index = "README.md"
extra = ["extra-pages/getting_started.md"]

[output]
static_dir = "static"
path = "docs"
base_url = "/cppdoc"

[doctests]
enable = true 
run = true
compiler_invocation = ["clang++", "{file}", "-o", "{out}", "-Iinclude", "-std=c++20"]
